# Generated by Django 3.1.4 on 2021-02-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210130_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptaskfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptaskshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_task_share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptaskstep',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_step', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_step', to=settings.AUTH_USER_MODEL),
        ),
    ]
