# Generated by Django 3.1.4 on 2021-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210202_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupshare',
            name='invite_uuid',
        ),
        migrations.RemoveField(
            model_name='grouptaskshare',
            name='invite_uuid',
        ),
        migrations.RemoveField(
            model_name='taskshare',
            name='invite_uuid',
        ),
        migrations.AddField(
            model_name='groupshare',
            name='invite_link',
            field=models.CharField(default=1, max_length=255, verbose_name='invite link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouptask',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouptaskshare',
            name='invite_link',
            field=models.CharField(default=1, max_length=255, verbose_name='invite link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskshare',
            name='invite_link',
            field=models.CharField(default=1, max_length=255, verbose_name='invite link'),
            preserve_default=False,
        ),
    ]
