# Generated by Django 3.1.4 on 2021-02-03 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210203_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
