# Generated by Django 3.1.4 on 2021-02-03 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_task_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='group_task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
