# Generated by Django 3.1.4 on 2021-02-04 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_group_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptaskshare',
            name='grouptask',
        ),
        migrations.AddField(
            model_name='grouptaskshare',
            name='group_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_task_share', to='app1.grouptask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupshare',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_share', to='app1.group'),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='app1.group'),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptaskfile',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_file', to='app1.group'),
        ),
        migrations.AlterField(
            model_name='grouptaskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_task_file', to='app1.grouptask'),
        ),
        migrations.AlterField(
            model_name='grouptaskstep',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_step', to='app1.group'),
        ),
        migrations.AlterField(
            model_name='grouptaskstep',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_task_step', to='app1.grouptask'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_file', to='app1.task'),
        ),
        migrations.AlterField(
            model_name='taskshare',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_to_share', to='app1.task'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='app1.task'),
        ),
    ]
